"use client";

import { useParams } from "next/navigation";

import { useProject } from "@/hooks/use-project";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";

export default function ReportPage() {
  const params = useParams<{ id: string }>();
  const { project, loading, error } = useProject(params.id);

  if (loading) return <Skeleton className="h-[40rem]" />;

  if (error || !project) {
    return (
      <Alert variant="warning">
        <AlertTitle>Unable to load SRS</AlertTitle>
        <AlertDescription>{error ?? "Project not found"}</AlertDescription>
      </Alert>
    );
  }

  const srs = project.srs_documents[0];

  return (
    <Card>
      <CardHeader>
        <CardTitle>Final Software Requirements Specification</CardTitle>
        <CardDescription>
          Complete SRS document generated by the SpecPilot AI workflow.
        </CardDescription>
      </CardHeader>
      <CardContent>
        {!srs ? (
          <Alert variant="info">
            <AlertTitle>SRS not generated yet</AlertTitle>
            <AlertDescription>
              Complete the workspace flow: analyze your idea, answer clarification questions,
              then return here for the full report.
            </AlertDescription>
          </Alert>
        ) : (
          <article className="prose max-w-none rounded-2xl border border-slate-200 bg-white p-6">
            <pre className="whitespace-pre-wrap font-sans text-sm leading-7 text-slate-700">
              {srs.content}
            </pre>
          </article>
        )}
      </CardContent>
    </Card>
  );
}
